version: '3'

services:
  db:
    image: mongo:6
    restart: always
    ports:
      - 27019:27017
    environment:
      MONGODB_DATABASE: superFlights
    volumes:
      - ./mongo-data:/data/db